apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: jobqueue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: mini-job-queue:local
          imagePullPolicy: Never
          command: ["/worker"]
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
